version: '2'
services:
    #
    #  ---> webserver onde a aplicação é executada
    #       Aqui ficam:
    #
    #          - webserver apache
    #          - plataforma (consultoria e prm "antigo")
    #
    api:
        build: ./build/webserver
        image: evoluttobr/api:latest
        container_name: api
        hostname: api
        restart: always
        command: /opt/env-config/autostart.sh
        ports:
            - "8090:443"
            - "8091:81"
        depends_on:
          - dbmaster
        volumes:
            - ../api:/opt/api
            - ../frontend:/opt/frontend


    #
    #  ---> banco de dados principal (mysql)
    #
    dbmaster:
        build: ./build/dbmaster
        image: evoluttobr/dbmaster:latest
        container_name: dbmaster
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

        volumes:
          # aqui fica o diretorio de dados da base mysql
          - ../data/mysql:/var/lib/mysql

          # essa pasta é montada para compartilhar dados entre o host e o container
          - ../data/shared:/opt/shared


    #
    #   ---> ambiente de desenvolvimento para o frontend
    #
    frontdev:
        build: ./build/frontdev
        image: omar331/frontdev:0.2
        container_name: frontdev
        hostname: frontdev
        restart: always
        command: /opt/scripts/start-dev-server.sh
        ports:
            - "7000:7000"
        volumes:
            - ../frontdev:/opt/dev



